# Hosts Kali Linux routed through Gluetun VPN
# Remember to set the environment variables WIREGUARD_PRIVATE_KEY, SERVER_COUNTRIES, and ROOT_PASSWORD before running

services:
  gluetun:
    image: qmcgaw/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "2222:22"
    environment:
      - TZ=UTC
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=$WIREGUARD_PRIVATE_KEY
      - SERVER_COUNTRIES=$SERVER_COUNTRIES
      - FREE_ONLY=true
      - EXTRA_SUBNETS=172.16.1.0/24
    healthcheck:
      test: ping -c 1 1.1.1.1 || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  kali:
    image: kali-linux:latest
    depends_on:
      - vpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: service:vpn
    ports:
      - "2222:22"
    volumes:
      - ./vault:/root/vault
    environment:
      - ROOT_PASSWORD=$ROOT_PASSWORD
    stdin_open: true
    tty: true
    restart: no