# Hosts Obsidian in a Selkies container

services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    ports:
      - 3001:3001
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TIMEZONE
      - MAX_RESOLUTION=3840x2160
      - NO_DECOR=true
      - SELKIES_ENABLE_SHARING=true
      - SELKIES_ENABLE_COLLAB=true
      - SELKIES_ENABLE_SHARED=true
    # Uncomment the following deploy block to enable Nvidia GPU acceleration (if the host supports it)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [compute,video,graphics,utility]
    shm_size: "1gb"
    restart: unless-stopped
